command_timeout = 1000

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = './'

[gcloud]
format = 'on [$symbol$project in $region]($style) '

[git_branch]
style = 'bold green'
symbol = 'î‚  '
truncation_length = 20
truncation_symbol = 'â€¦'

[git_status]
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
format = '([$all_status$ahead_behind]($style) )'
modified = '${count}ó°‡‚ '
stashed = '${count}ó°¼œ '
untracked = '${count}? '
style = 'bold green'

[python]
symbol = 'ğŸ '
pyenv_version_name = true

[status]
symbol = 'âŒ'
success_symbol = 'ğŸ’š'
format = '[$symbol $status]($style) '
map_symbol = false
disabled = false
